apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
spec:
  selector:
    matchLabels:
      app: docs
  replicas: 1
  template:
    metadata:
      labels:
        app: docs
    spec:
      containers:
      - name: docs
        image: index.docker.io/<userID>/docs:staging-d5208850
        imagePullPolicy: Always
        ports:
         - containerPort: 4000
